version: '3.9'

services:
  airports_app:
    build: .
    container_name: airports_app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://host.docker.internal:5432/demo
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "8081:8081"
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
